# Workflow name
name: CI Build

# Events that will trigger this workflow
on:
  # workflow_dispatch allows us to run this workflow manually from the Actions tab on GH
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:

    # OS to run on
    runs-on: ubuntu-latest

    # CLI steps for the workflow
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Do a Maven local publish of the AOP Plugin
        run: ./publishLocal.sh

      - name: Gradle Build
        run: ./gradlew build